### ISSUE TITLE
expose google params code

### ISSUE THREAD

**Issue by atomGit** [serj-kzv/mozlz4-edit#5]
you have some code in the add-on that apparently retrieves the google search parameters - you might want to mention that, and how to use it, in the add-on description, as well as making this tool available in the add-on UI

**Comment by serj-kzv** [comment]
To get google params I just parsed a google html page with a JavaScript once and inserted the result to ```engines.json``` file. The code is not used in the addon per execution, the code was used once to get google params. The google page with params can be changed in any moment by google and the JavaScript code will become useless. I saved the JavaScript file with the code to the addon code as a notice and a help for those people who would want to do some similar thing.

I am not going to create UI to retrieve google params because it will be totally new different application and it takes to many amount of work compare with a purpose of the addon. :)

With the latest release I added possibility to edit ```engines.json``` manually. Anyone can make their own engine list with their own params.
